### ISSUE TITLE
Can we play online audio file. 

### ISSUE THREAD

**Issue by Saqib92** [Cap-go/native-audio#1]
**Is your feature request related to a problem? Please describe.**
Can we Play Online Audio URL?

**Describe the solution you'd like**
It should be able to play audio file hosted on server as adding multiple files in app bundle will increase app size. 

**How this plugin is different from community plugin?**
https://github.com/capacitor-community/native-audio

**Comment by riderx** [comment]
Hey @Saqib92 thanks for your questions, for now, it's not possible to play sound from URL, but it could be nice!
I have forked the one from the community because most of the last fix of the plugin have been made by me and took weeks to be merged.
So since I have more than 10 plugins in this org and make them great is my full-time job, it makes sense. 
I hope here to create a better dynamic than in capacitor-community where some frustration appeared over time.

**Comment by Saqib92** [comment]
> Hey @Saqib92 thanks for your questions, for now, it's not possible to play sound from URL, but it could be nice! I have forked the one from the community because most of the last fix of the plugin have been made by me and took weeks to be merged. So since I have more than 10 plugins in this org and make them great is my full-time job, it makes sense. I hope here to create a better dynamic than in capacitor-community where some frustration appeared over time.

this is very kind of you for doing these updates. Thank you.

**Comment by Saqib92** [comment]
I am currently using https://github.com/apache/cordova-plugin-media to play audio files from URL. You can have a look it will help you to add this feature. I wish i could help you but i have no Native Java or Swift experience thats why i am limited.

**Comment by BjoernRave** [comment]
I would also really like to have thise feature

**Comment by ipehimanshu** [comment]
Hello

so is there any plugin which work for capacitor ?

**Comment by Saqib92** [comment]
> Hello
> 
> so is there any plugin which work for capacitor ?

https://github.com/Cap-go/native-audio/issues/1#issuecomment-1298554266

**Comment by hvma411** [comment]
Any updates on this feature? I'm currently using https://github.com/apache/cordova-plugin-media for playing sounds from online urls but I can't resume playing music from other app (for example from spotify after sound has been played), or I don't know how. As far as I tested it is possible with cap-go to play sound and return to playing music from other app

**Comment by riderx** [comment]
Hey u just added the feature in 6.2.0 let me know if that works for you
