### ISSUE TITLE
Capacitor 6 Support

### ISSUE THREAD

**Issue by chriswheaton** [Cap-go/native-audio#107]
### Summary
Capacitor 6 has been released, bringing support for Android 14 and iOS 17.
https://ionic.io/blog/announcing-capacitor-6-0

Could you inform us of the timeline for supporting Capacitor 6 with this plugin?

### Desired Behavior
Works with Capacitor 6.

### Possible Solution
https://capacitorjs.com/docs/updating/plugins/6-0

**Comment by Mdemol** [comment]
Also waiting for the upgrade.

**Comment by Mdemol** [comment]
To make it easier and faster to implement you can view [this](https://github.com/capacitor-community/native-audio/pull/101) PR from the official non maintained repo.

**Comment by riderx** [comment]
Hello the plugin has been updates to v6
