### ISSUE TITLE
Crash issues in preload audio on iOS with version 6.1.16 and audio issues with vidyo.io video call on version 6.2.7

### ISSUE THREAD

**Issue by adarshcitrus** [Cap-go/native-audio#128]
Description:

Hello,

I am experiencing issues with the @capgo/native-audio library on iOS with Ionic 7 and angular 17

Problem 1: Crash Issues

Version: 6.1.16
Description: The app crashes when preloading audio.
Steps to Reproduce:
Call the preload method.
Observe the crash.

Problem 2: Audio Issues with vidyo.io Video Call

Version: 6.2.7
Description: After updating to 6.2.7, the crash issue is resolved. However, the audio for vidyo.io video calls stops working.
Steps to Reproduce:
Update to version 6.2.7.
Initiate a vidyo.io video call.
Observe that the audio is not working.

iOS Version: Issue obtained in 16 and 17
XCode version 15.3
Please let me know if you need any further information or assistance in reproducing these issues.

Thank you!

**Comment by riderx** [comment]
Can you have look with latest version i fixed ios and android
