### ISSUE TITLE
Time param not optional on play method

### ISSUE THREAD

**Issue by mcfarljw** [Cap-go/native-audio#13]
**Describe the bug**
This could be an issue with the docs but they mentioned that the time param is optional but the definition typings don't allow it to be optional (see code link below).

https://github.com/Cap-go/native-audio/blob/6b071d63625a5ff570df1b4bb5e2c13c5449d66c/src/definitions.ts#L4

**To Reproduce**

**Expected behavior**
The `time` param of the `play` method is optional defaulting to 0 if not provided.

**Comment by riderx** [comment]
Thanks for the report, i updated the defenition
