### ISSUE TITLE
"complete" event not dispatched on Android after playing a remote audio asset

### ISSUE THREAD

**Issue by sgilroy** [Cap-go/native-audio#134]
**Describe the bug**
When using `NativeAudio.addListener('complete', ...)` to listen for the complete event, the event should be dispatched after the audio finishes playing. On Android, when playing an asset from a remote url (https://) the complete event is never dispatched.

**To Reproduce**
1. Prepare a project that targets Android
2. `NativeAudio.preload({ assetId: "sample", assetPath: "https://download.samplelib.com/mp3/sample-3s.mp3", audioChannelNum: 1, isUrl: false })`
3. `NativeAudio.addListener("complete", event => console.log("complete", event))`
4. `NativeAudio.play({ assetId: "sample" })`

**Expected behavior**
The complete event should be logged, but it is not.

**Comment by co-dax** [comment]
@riderx Can this please be merged??

**Comment by riderx** [comment]
thanks for the work
