### ISSUE TITLE
 Audio is not played

### ISSUE THREAD

**Issue by Lucas-Wanat** [Cap-go/native-audio#17]
In my project with capacitor 3 (due to serial bluetooth) there is a problem, where no error is shown but the sound does not play, I analyzed everything but nothing happens, and before it worked normally.

Thanks in advance.

Ps: I need to solve it urgently.

**Comment by riderx** [comment]
hello in IOS or Android ?

**Comment by Lucas-Wanat** [comment]
Good morning, actually the problem was solved using npx cap sync and copy,
the project is in android. Still thanks for the service.

Em ter., 24 de jan. de 2023 às 04:08, Martin DONADIEU <
***@***.***> escreveu:
