### ISSUE TITLE
capacitorExports is not defined

### ISSUE THREAD

**Issue by Martint06** [Cap-go/native-audio#22]
**Describe the bug**
I just install your package, and try to play an audio file.
I got this error : `capacitorExports is not defined`
And also `Uncaught (in promise) AssetId already exists. Unload first if like to change!`

I'm working with NextJs and capacitorJs
`"@capacitor/core": "^4.6.3",`
`"next": "13.1.6",`

In my file : 
`import { NativeAudio } from "@capgo/native-audio";`
`NativeAudio.preload({
		assetId: "medusa",
		assetPath: '../../sounds/medusa.mp3',
		audioChannelNum: 1,
		isUrl: false,
	});`
`NativeAudio.play({
			assetId: "medusa",
			// time: 6.0 - seek time
		});`

I can't build to try on android or ios, so actually I run my code with `npm run dev`

If anyone have an idea.
Thanksss

**Comment by riderx** [comment]
can you share a demo project ?

**Comment by youngerjo** [comment]
I got the error `ReferenceError: capacitorExports is not defined` in my Next.js + Capacitor project and finally found a solution for my case. Try this.

before:
`import { NativeAudio } from "@capgo/native-audio"`

after:
`import { NativeAudio } from "@capgo/native-audio/dist/esm"`

Might not the best solution, but it works anyway :)

**Comment by riderx** [comment]
@Martint06 did you tested it?

**Comment by Martint06** [comment]
> I got the error `ReferenceError: capacitorExports is not defined` in my Next.js + Capacitor project and finally found a solution for my case. Try this.
> 
> before: `import { NativeAudio } from "@capgo/native-audio"`
> 
> after: `import { NativeAudio } from "@capgo/native-audio/dist/esm"`
> 
> Might not the best solution, but it works anyway :)

This solve my problem ! Thank you
