### ISSUE TITLE
iOS - Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by acurrieclark** [Cap-go/native-audio#27]
**Describe the bug**
I am getting the above error when I try to preload mp3 files.

**To Reproduce**

1. Add the plugin.
2. Preload an mp3 from eg `assets/sounds/music.mp3`
3. Build and launch app on iOS
4. Observe fatal error

**Expected behavior**
The file preloads properly and the application doesn't crash. NB. The issue does not occur in `v5.1.3`

**Smartphone (please complete the following information):**
iPhone running latest iOS 16

**Additional context**
This is the line which throws the error
https://github.com/Cap-go/native-audio/blob/ca819f42fbcfc6e9fd3769f7160c13fc0e948afd/ios/Plugin/AudioAsset.swift#L31

**Comment by acurrieclark** [comment]
I did have some success in mitigating the error by replacing the line with:

```swift
let pathUrl: URL = URL(string: path)
guard let pathUrl = pathUrl else { return }
```

but I am unsure if this is actually fixing the issue

**Comment by riderx** [comment]
By doing this it mean preload will not preload. 
do you play the sound like that ?

**Comment by acurrieclark** [comment]
Did a little more digging, and it turned out to be one of my paths has a space in it. PR submitted with a fix
