### ISSUE TITLE
iOS - sounds do not respect the hardware mute switch

### ISSUE THREAD

**Issue by acurrieclark** [Cap-go/native-audio#28]
In the current version, the mute switch on an iPhone has no effect and the sound plays regardless.

**Describe the solution you'd like**
It should be possible to mute sounds when the hardware switch is set to "mute"

**Comment by acurrieclark** [comment]
Configure only has `focus` and `fade` parameters, so I am not sure that is the right option here.

I could be wrong, but I would have thought that most people would want the sound to **not** play when muted?

**Comment by acurrieclark** [comment]
I ended up using the `focus` config setting to stop sounds fading out already playing sounds, and it turned out that also fixed the hardware switch issue.

Thanks for your help

**Comment by riderx** [comment]
@acurrieclark interestingly, more dev where interested to not respect user choice, and even in my app i had many time the user feedback why there no sound 🤣, until i made this setting.
Seems Apple is getting rid of it this year, this will no longer be an issue ahah.

Yes focus make the trick, honestly the Apple setup around sound was super hard to understand and even now i'm not sure to get it all.
I'm happy you found your way !

**Comment by webdog-rich** [comment]
@acurrieclark do you have a reference for "Seems Apple is getting rid of it this year, this will no longer be an issue ahah." Thanks

**Comment by acurrieclark** [comment]
@webdog-rich do you mean @riderx ?

**Comment by webdog-rich** [comment]
Sorry, yes
