### ISSUE TITLE
Capacitor v5 support

### ISSUE THREAD

**Issue by reslear** [Cap-go/native-audio#33]
need fixes for android support 

https://capacitorjs.com/docs/updating/plugins/5-0
or 
`npx @capacitor/plugin-migration-v4-to-v5@latest`

**Comment by konradm** [comment]
I'm not sure if I understand. Do I need to do something?

**Comment by riderx** [comment]
i'm currently a bit busy but if anymore is open to help there an easy guide to do it.
https://capacitorjs.com/docs/updating/plugins/5-0
if you do a Pr i will accept it

**Comment by riderx** [comment]
Done !
