### ISSUE TITLE
capacitor 5 Error: "NativeAudio" plugin is not implemented on android

### ISSUE THREAD

**Issue by farshidpg** [Cap-go/native-audio#35]
**Describe the bug**
Hello after update my project to cap 5 and update ```"Cap-go/native-audio"``` to ```6.0.8``` I get this error on  when call ```NativeAudio``` any method 

I'm sure about ```cap sync``` and ```cap update```

This problem only happen when we publish the app on play store  with aab build ( akp not tested in play store because tehere is no way anymore for upload apk in play store )

here is  part of my package.json

```
"@capacitor/android": "^5.0.4",
"@capacitor/app": "^5.0.2",
"@capacitor/core": "^5.0.4",
"@capacitor/ios": "^5.0.4",
"@capgo/native-audio": "^6.0.7",
"@ionic/core": "^7.0.9",
"@ionic/vue": "^7.0.9",
```

**Comment by sovaltd** [comment]
This problem only happen when we publish the app on play store.

**Comment by dferenc-netwizzy** [comment]
> This problem only happen when we publish the app on play store.

Just published an internal test application using `aab` through `playstore` and while first seemingly i had issues with the plugin (local `apk` to device worked, but not the published `aab`) i forgot the detail that the propagation to the store isn't instant.
Once the binary is uploaded, it can take some time until the ***new version*** shows up as available/update.

The error doesn't show up for me , looks all good so far, using:
* `capacitor@^5.0.0`
* `angular@^15.0.4`
* `@capgo/native-audio@^6.0.10`

Make sure that the app You are testing/uploading to the store is the same version that works as `apk`.

**Comment by kyoz** [comment]
That's odd, my app using latest version and it working normally. You ensure everything work, make sure you have rebuild the source.

```sh
ng build && npx cap copy && npx cap sync
```
