### ISSUE TITLE
[Android] `await NativeAudio.configure(...)` doesn't return

### ISSUE THREAD

**Issue by HarelM** [Cap-go/native-audio#48]
**Describe the bug**
When calling `await NativeAudio.configure(...)` the promise never returns

**To Reproduce**
1. call configure with await

**Expected behavior**
The `configure` method should be either not return a promise in typescript or returned when awaited

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung S20
 - OS: Android 13

**Additional context**
I have tried to add `call.resolve()` in `configure` in `NativeAudio.java` at the end of the configure method and it seems to solve this issue, but I'm not sure what was intended here.
Let me know if you want me to open a PR.

![image](https://github.com/Cap-go/native-audio/assets/3269297/51fd9509-f761-4405-9d5e-f5785f6ad1c1)

**Comment by HarelM** [comment]
Removing the `await` from `await NativeAudio.configure(...)` also solves this issue.
So it might be that only the typescript definition file needs to be updated...

**Comment by riderx** [comment]
Thanks for raising this, you are right it should call the resolve, do you want to do a PR and i accept your change? i think that better since you fixed it

**Comment by HarelM** [comment]
I opened #50 feel free to fix it differently if you think there's a better solution.
Let me know when a new version is available so I can update my code with it.

**Comment by HarelM** [comment]
@riderx any chance for a new version release?

**Comment by riderx** [comment]
Sorry it was issue running the CI/CD i manually released

**Comment by HarelM** [comment]
Thanks! keep up the good work!
As a side note, there's an "maintained: no! as of 2022" in the readme... not sure if you want to fix this or not.
![image](https://github.com/Cap-go/native-audio/assets/3269297/3ddcd0f2-dddd-4a38-b340-f283b6885db9)

**Comment by riderx** [comment]
Thanks I just fixed it, it needs to be updated each year that a bit stupid :/

**Comment by HarelM** [comment]
BTW, I don't see this issue or the linked PR in the changelog...

**Comment by riderx** [comment]
That normal the CI/CD was failing so I just published I will check the CI this w
