### ISSUE TITLE
 nativeAudio.addListener not functioning as expected

### ISSUE THREAD

**Issue by coxozo** [Cap-go/native-audio#64]
**Describe the bug**
I'm experiencing an issue with the nativeAudio.addListener method in my application. It doesn't seem to be working as expected. When attempting to use it in conjunction with my code, which plays a series of audio files sequentially, the event listener doesn't trigger when audio playback is completed.

**To Reproduce**
```
import { NativeAudio, PreloadOptions } from "@capgo/native-audio";

class AudioPlayer {
  private nativeAudio = NativeAudio;
  private audioUrls: string[] = [];
  private currentIndex: number = 0;

  async playAudioArray(audioUrls: string[]) {
    this.audioUrls = audioUrls;
    this.currentIndex = 0;

    // Preload the first audio
    await this.preloadNextAudio();

    // Start playing
    await this.playCurrentAudio();
  }

  private async preloadNextAudio() {
    if (this.currentIndex < this.audioUrls.length) {
      const assetPath = this.audioUrls[this.currentIndex];
      const assetId = `audio_${this.currentIndex}`;

      const preloadOptions: PreloadOptions = {
        assetPath,
        assetId,
        // Other preload options, set as needed
      };

      await this.nativeAudio.preload(preloadOptions);
    }
  }

  private async playCurrentAudio() {
    if (this.currentIndex < this.audioUrls.length) {
      const assetId = `audio_${this.currentIndex}`;

      // Play the current audio
      await this.nativeAudio.play({ assetId });

      // Listen for the completion event
      const listener = async (event: { assetId: string }) => {
        if (event.assetId === assetId) {
          // Current audio playback is complete
          this.currentIndex++;

          if (this.currentIndex < this.audioUrls.length) {
            // Preload and play the next audio
            await this.preloadNextAudio();
            await this.playCurrentAudio();
          }
        }
      };

      // Add a completion event listener
      const listenerHandle = await this.nativeAudio.addListener(
        "complete",
        listener
      );
    }
  }
}

export default AudioPlayer;

```
```
const audioPlayer= new AudioPlayer();
audioPlayer.playAudioArray([url, url]);
```
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 116.0.5845.188

**Comment by riderx** [comment]
Do you mean the issue is only on chrome Windows ?

**Comment by webnautics** [comment]
@coxozo did you solved this? I am not sure if complete means complete with loading audio here and not completion of playing!

```
const audioComplete: CompletedListener = async (event) => {
  // do something
}

NativeAudio.preload({
    assetId: ..,
    assetPath: ..,
    audioChannelNum: 1,
    isUrl: true,
  })
    .then(() => {
      NativeAudio.play({ assetId: .. })
      const handle = NativeAudio.addListener('complete', audioComplete)
      console.log(handle)
})
```

Promise state in handle is 'fulfilled' immediately in my code above!

**Comment by coxozo** [comment]
> @coxozo did you solved this? I am not sure if complete means complete with loading audio here and not completion of playing!你解决了吗？我不确定complete是否意味着在这里完成加载音频而不是完成播放！
> 
> ```
> const audioComplete: CompletedListener = async (event) => {
>   // do something
> }
> 
> NativeAudio.preload({
>     assetId: ..,
>     assetPath: ..,
>     audioChannelNum: 1,
>     isUrl: true,
>   })
>     .then(() => {
>       NativeAudio.play({ assetId: .. })
>       const handle = NativeAudio.addListener('complete', audioComplete)
>       console.log(handle)
> })
> ```
> 
> Promise state in handle is 'fulfilled' immediately in my code above!在我上面的代码中，句柄中的 promise 状态立即“实现”！

It seems my initial approach may have been incorrect. I've switched to using a different solution:  ```capacitor-plugin-playlist``` which effectively manages audio playlist playback.
