### ISSUE TITLE
"Eating up" the first fractions of a second of audio on iOS

### ISSUE THREAD

**Issue by Brullworfel** [Cap-go/native-audio#69]
**Describe the bug**
After updating from 6.0.19 to 6.1.8 the audio started to "eat up" the first fractions of a second.

**To Reproduce**
1. Try to play short mp3 audio file without any silence in the beginning on iOS. File showed on the video can be downloaded from [here](https://www.dropbox.com/scl/fi/phpgbmd0hcej8etdyj3s0/audio_en-GB-Standard-B_2ea802eeb4485cf32398e8fa1c85d0be431cfa53e21c8cae1e413c628eef2c0c.mp3?rlkey=fiq4fbgnqppwhgbsby4dchd1n&dl=0).
2. You will not be able to hear the first fractions of a second of the audio. The problem is clearly audible in this [video](https://www.youtube.com/shorts/j-rux1a8KdQ).

**Expected behavior**
Audio is played completely from start to finish, without cutting anything off. You can hear expected behaviour on the same device, same iOS, same project, but with with version 6.019 on this [video](https://youtube.com/shorts/b-sOO_XE3iE?feature=share).

**Desktop (please complete the following information):**
 Desktop is ok - tested on Chrome / Mac.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Mini
 - OS: iOS 17.0.3
 - Capacitor 5.5.1
 - Version 6.1.8

**Additional context**
Didn't test on Android.

**Comment by riderx** [comment]
thanks for report i will have a look on it now

**Comment by riderx** [comment]
just released 6.1.35 can you check if that fixed?

**Comment by Brullworfel** [comment]
We are testing on 6.2.2 currently - will let you know tomorrow, thank you @riderx !

**Comment by Brullworfel** [comment]
@riderx works fine now, thank you!

**Comment by riderx** [comment]
You are welcome !
