### ISSUE TITLE
Where to place audio files?

### ISSUE THREAD

**Issue by RaddishIoW** [Cap-go/native-audio#9]
Hi there,

It's not at all clear where you should place the audio files, or what path to use to point to them? Putting them "with the rest of [my] source" doesn't really clear it up, as doing that, without then copying those files into the iOS or Android assets in the right places, doesn't work for my setup (Vite and Capacitor).

Any pointers that you could give in the docs?

**Comment by RaddishIoW** [comment]
Just found that the plugin is looking in `<root>/assets/sounds/`, at least on web... this would be good to document properly...

**Comment by riderx** [comment]
Hello thanks for the feedback, i can improve that for sure !
I use vite/vue capacitor in my project as well.
For iOS and android, the only need is to have the sound present in your build folder.
So if in production build your file is in `build/sound/file1.mp3` the path in the plugin need to be `sound/file1.mp3`
I will update the path for web to have less opinion and just follow what you give

**Comment by TheRealPingWin** [comment]
Hi,
I'm building an angular/capacitor app and I use your library to play sound effects on native.
However I can't make it work on ios. On android i placed the sound files in android/app/src/main/assets and works well. On ios I checked the example projects where you store the files and I created a sounds folder in ios/app/app and placed the files there, but it doesn't work.

**Comment by riderx** [comment]
The sound file don't need to be in IOS and android folder anymore.
They have to be in your build folder like js, html and css @RaddishIoW

**Comment by likerRr** [comment]
@riderx hi! you still didn't document this properly.. I put my files under build folder, but they don't play

**Comment by likerRr** [comment]
Thanks, @riderx ! Now it's much better, but if I were you, I would put it under preparation section, cause in comments its a little bit harder to understand which info is important to read.

Anyway thanks a lot for your work. Your plugin is the only working solution for playing audio I've found

**Comment by riderx** [comment]
Fixed thanks. lot !

**Comment by reslear** [comment]
or better from assets

```ts
const { default: assetPath } = await import(`@/assets/sounds/${asset}.mp3`)

await NativeAudio.preload({
  assetId: asset,
  assetPath,
})

```

**Comment by riderx** [comment]
@reslear  i believe that not doable :/
Since this path is loaded in native.
So if you import in JS it mean we need to get the binary file in js send it in binary to native and then load it in native.
That will be way slower and more complex.
