### ISSUE TITLE
Focus parameter does not work and sound is not focused

### ISSUE THREAD

**Issue by hvma411** [Cap-go/native-audio#98]
**Describe the bug**
NativeAudio.configure({ focus: true }) does not work anymore. When I play some music in other app (for example Spotify) and I use some sound in my app then it is not focusing my sound and I can hear both sounds (spotify and my app sound) at the same time.

**To Reproduce**
Play any sound using this plugin while other app plays music in background

**Expected behavior**
App should focus on app sound and after sound finish playing then it should focus again on background sound from other app

**Smartphone (please complete the following information):**
 - Device: iPhone 15, iPhone 15 Pro, iPhone 12 mini, Pixel 5
 - OS: newest iOS and Android

**Additional context**
I have newest version of plugin and my cap doctor is below:

```Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/ios: 5.4.2

[success] iOS looking great! 👌
[success] Android looking great! 👌```

**Comment by riderx** [comment]
Both platforms ?

**Comment by riderx** [comment]
thanks for the report i added a fix to prevent this to happen in 6.1.37 can you have a look and tell me if that work for you ?

**Comment by hvma411** [comment]
@riderx thank you for very fast response. I couldn't find 6.1.37 version to install but i installed newest one 6.2.0 so I'll test it in about 1 hour and I'll let you know if it works.

**Comment by hvma411** [comment]
@riderx I tested newest version and now focus works but only partially. Sound from my app is focused but it is not loosing focus after sound stops playing. I tried stops my sound manually and after that unload this sound but it does not help. I have to close my app, to bring focus back to other app with music playing in background.

**Comment by riderx** [comment]
Ok thanks, i will look a bit more on that

**Comment by riderx** [comment]
ok, it was missing the unfocus detection, I added it in 6.2.1

**Comment by hvma411** [comment]
Many thanks for your help, it looks like it is working now.

**Comment by syirilrakhulh** [comment]
It's broken again in version 6.4.23? Because when I try play music in background, I still can hear the background music and sound from native audio. I already set focus to true.

**Comment by riderx** [comment]
Can you create new issue ? We didn’t change code about that so it’s probably a new os version issue
